# Generated by Django 3.0.4 on 2020-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Mail', models.EmailField(max_length=254)),
                ('Phnno', models.BigIntegerField()),
                ('worker', models.BooleanField()),
                ('work', models.CharField(max_length=50)),
                ('user_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
