# Generated by Django 3.0.4 on 2020-12-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('work', models.CharField(max_length=25)),
                ('worker', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='p_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('work', models.CharField(max_length=25)),
                ('worker', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=25)),
                ('part', models.CharField(max_length=25)),
            ],
        ),
    ]
